/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.intent_exchange.drone_highway.api;

import javax.annotation.Generated;
import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.intent_exchange.drone_highway.entity.CurrentLocationEntity;
import com.intent_exchange.drone_highway.entity.DroneLocationNotificationEntity;
import com.intent_exchange.drone_highway.entity.ErrorResponseEntity;
import com.intent_exchange.drone_highway.exception.CurrentLocationException;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2024-12-13T05:27:23.828338500Z[Etc/UTC]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "DroneLocation", description = "安全管理支援(A-1-4)のコントローラクラス。")
public interface DroneLocationApi {

  /**
   * POST /drone-location-notification : 運行中ドローンの位置情報の通知 指定されたエリア内のドローンのテレメトリ情報を USS から航路の安全管理
   * (A-1-4) へ指定されたエンドポイントに通知する。
   *
   * @param droneLocationNotificationEntity (required)
   * @return 正常終了 (status code 204)
   */
  @Operation(operationId = "notifyDroneLocation", summary = "運行中ドローンの位置情報の通知",
      description = "指定されたエリア内のドローンのテレメトリ情報を USS から航路の安全管理 (A-1-4) へ指定されたエンドポイントに通知する。",
      tags = {"DroneLocation"},
      responses = {@ApiResponse(responseCode = "204", description = "正常終了")})
  @RequestMapping(method = RequestMethod.POST, value = "/drone-location-notification",
      consumes = {"application/json"})

  ResponseEntity<Void> notifyDroneLocation(@Parameter(name = "DroneLocationNotificationEntity",
      description = "",
      required = true) @Valid @RequestBody DroneLocationNotificationEntity droneLocationNotificationEntity);

  /**
   * GET /get-current-location/{reservationId} : 現在のドローンの位置情報取得 航路予約毎の識別 ID に該当するドローンの現在の位置情報を取得する。
   * この API が実行された時点で、5 秒前まで最新の情報を取得する。
   *
   * @param reservationId 航路予約毎の識別 ID (required)
   * @return 現在のドローンの位置情報 (status code 200) or 入力チェックエラー (status code 400) or 航路予約 ID が DB
   *         に存在しなかった場合、または、5秒前までの情報はなかった場合 (status code 404) or サーバーエラー (status code 500)
   * @throws MethodArgumentNotValidException
   * @throws CurrentLocationException
   */
  @Operation(operationId = "getCurrentLocation", summary = "現在のドローンの位置情報取得",
      description = "航路予約毎の識別 ID に該当するドローンの現在の位置情報を取得する。   この API が実行された時点で、5 秒前まで最新の情報を取得する。   ",
      tags = {"DroneLocation"},
      responses = {
          @ApiResponse(responseCode = "200", description = "現在のドローンの位置情報",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = CurrentLocationEntity.class))}),
          @ApiResponse(responseCode = "400", description = "入力チェックエラー",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponseEntity.class))}),
          @ApiResponse(responseCode = "404",
              description = "航路予約 ID が DB に存在しなかった場合、または、5秒前までの情報はなかった場合",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponseEntity.class))}),
          @ApiResponse(responseCode = "500", description = "サーバーエラー",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponseEntity.class))})})
  @RequestMapping(method = RequestMethod.GET, value = "/get-current-location/{reservationId}",
      produces = {"application/json"})

  ResponseEntity<CurrentLocationEntity> getCurrentLocation(
      @Parameter(name = "reservationId", description = "航路予約毎の識別 ID", required = true,
          in = ParameterIn.PATH) @PathVariable("reservationId") String reservationId)
      throws MethodArgumentNotValidException, CurrentLocationException;

}

