/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.intent_exchange.drone_highway.api;

import com.intent_exchange.drone_highway.entity.ErrorResponseEntity;
import com.intent_exchange.drone_highway.entity.MonitoringNotificationDestinationRequestEntity;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-12-16T10:32:09.677292+09:00[Asia/Tokyo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "MonitoringNotification", description = "第三者立入監視情報通知のコントローラクラス。")
public interface MonitoringNotificationApi {

    /**
     * PUT /monitoring-notification-destination-change : 第三者立入監視情報の通知の変更
     * データプロバイダに登録した情報変更通知先を変更する。
     *
     * @param monitoringNotificationDestinationRequestEntity  (optional)
     * @return 正常終了 (status code 204)
     *         or 入力チェックエラー (status code 400)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "changeMonitoringNotificationDestination",
        summary = "第三者立入監視情報の通知の変更",
        description = "データプロバイダに登録した情報変更通知先を変更する。",
        tags = { "MonitoringNotification" },
        responses = {
            @ApiResponse(responseCode = "204", description = "正常終了"),
            @ApiResponse(responseCode = "400", description = "入力チェックエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/monitoring-notification-destination-change",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> changeMonitoringNotificationDestination(
        @Parameter(name = "MonitoringNotificationDestinationRequestEntity", description = "") @Valid @RequestBody(required = false) MonitoringNotificationDestinationRequestEntity monitoringNotificationDestinationRequestEntity
    );


    /**
     * DELETE /monitoring-notification-destination-deletion : 第三者立入監視情報の通知の変更
     * データプロバイダに登録した情報変更通知先を削除する。
     *
     * @return 正常終了 (status code 204)
     *         or 入力チェックエラー (status code 400)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "deleteMonitoringNotificationDestination",
        summary = "第三者立入監視情報の通知の変更",
        description = "データプロバイダに登録した情報変更通知先を削除する。",
        tags = { "MonitoringNotification" },
        responses = {
            @ApiResponse(responseCode = "204", description = "正常終了"),
            @ApiResponse(responseCode = "400", description = "入力チェックエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/monitoring-notification-destination-deletion",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteMonitoringNotificationDestination(
        
    );


    /**
     * POST /monitoring-notification-destination-registration : 第三者立入監視情報の通知の登録
     * 変更があった場合に通知(Subscribe)を行うため、航路の安全管理支援(A-1-4)の通知先をデータプロバイダに登録する。
     *
     * @param monitoringNotificationDestinationRequestEntity  (optional)
     * @return 正常終了 (status code 201)
     *         or 入力チェックエラー (status code 400)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "registerMonitoringNotificationDestination",
        summary = "第三者立入監視情報の通知の登録",
        description = "変更があった場合に通知(Subscribe)を行うため、航路の安全管理支援(A-1-4)の通知先をデータプロバイダに登録する。",
        tags = { "MonitoringNotification" },
        responses = {
            @ApiResponse(responseCode = "201", description = "正常終了"),
            @ApiResponse(responseCode = "400", description = "入力チェックエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/monitoring-notification-destination-registration",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> registerMonitoringNotificationDestination(
        @Parameter(name = "MonitoringNotificationDestinationRequestEntity", description = "") @Valid @RequestBody(required = false) MonitoringNotificationDestinationRequestEntity monitoringNotificationDestinationRequestEntity
    );

}

