
openapi: 3.0.0
info:
  title: 安全管理支援(SafetyManagement) API
  version: 1.0.0
tags:
  - name: UaslReservation
    description: 安全管理支援(SafetyManagement)のコントローラクラス。
paths:
  /uasl-reservation-notification:
    post:
      summary: 航路予約情報の通知
      description: 機体ID(リモートID)と航路予約毎の識別IDを受信し、航路予約へ航路予約毎の識別IDを送信し予約情報を受信、機体ID(リモートID)と紐づけ保存します。
      operationId: notifyUaslReservation
      tags:
        - UaslReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UaslReservationNotificationEntity'
      responses:
        '201':
          description: 作成成功
        '400':
          description: 入力チェックエラー
          $ref: '#/components/responses/400'
        '500':
          description: サーバーエラー
          $ref: '#/components/responses/500'
  /uasl-reservation-deletion/{uaslReservationId}:
    delete:
      summary: 航路予約情報の削除
      description: 航路の安全管理支援(SafetyManagement)へ通知した航路予約情報を削除する。
      operationId: deleteUaslReservation
      tags:
        - UaslReservation
      parameters:
        - $ref: "#/components/parameters/uaslReservationId"
      responses:
        '204':
          description: 削除成功
        '400':
          description: 入力チェックエラー
          $ref: '#/components/responses/400'
        '500':
          description: サーバーエラー
          $ref: '#/components/responses/500'
components:
  parameters:
    uaslReservationId:
      name: uaslReservationId
      in: path
      required: true
      schema:
        type: string
      description: 航路予約毎の識別ID
  schemas:
    UaslReservationNotificationEntity:
      type: object
      description: 機体ID(リモートID)と航路予約毎の識別IDを受信し、予約情報を保存API用のentity
      properties:
        aircraftId:
          type: string
          x-baseName: aircraftId
          description: 機体ID
        uaslReservationId:
          type: string
          x-baseName: uaslReservationId
          description: 航路予約毎の識別ID
      required:
        - aircraftId
        - uaslReservationId
    ErrorResponseEntity:
      type: object
      description: エラー時のResponse用Entity
      properties:
        code:
          type: string
          description: エラーコード
          example: "400"
        message:
          type: string
          description: エラーメッセージ
          example: "入力チェックエラー"
        description:
          type: string
          description: 詳細
          example: "0 以上の値にしてください"
  responses:
    '400':
      description: 入力チェックエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseEntity'
    '500':
      description: サーバーエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseEntity'
