openapi: 3.0.0
info:
  title: 安全管理支援(SafetyManagement) API
  version: 1.0.0
tags:
  - name: ConformityAssessment
    description: 安全管理支援(SafetyManagement)のコントローラクラス。
paths:
  /conformity-assessment:
    post:
      summary: 航路の適合性評価実行
      description: 航路IDと予約日時、機体情報を受信し、航路予約へ航路の適合性評価の結果を送信します。
      operationId: executionConformityAssessment
      tags:
        - ConformityAssessment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConformityAssessmentExecutionEntity'
      responses:
        '200':
          description: 適合性評価結果OK
        '400':
          description: 入力チェックエラー
          $ref: '#/components/responses/400'
        '500':
          description: サーバーエラー
          $ref: '#/components/responses/500'
components:
  schemas:
    ConformityAssessmentExecutionEntity:
      type: object
      description: 航路の適合性評価実行API用のentity
      properties:
        uaslId:
          type: string
          description: 航路ID
        startAt:
          type: string 
          format: date-time
          description: 予約開始日時
        endAt:
          type: string
          format: date-time
          description: 予約終了日時
        aircraftInfo:
          type: string
          description: 機体情報
      required:
        - uaslId
        - startAt
        - endAt
        - aircraftInfo
    ErrorResponseEntity:
      type: object
      description: エラー時のResponse用Entity
      properties:
        code:
          type: string
          description: エラーコード
          example: "400"
        message:
          type: string
          description: エラーメッセージ
          example: "入力チェックエラー"
        description:
          type: string
          description: 詳細
          example: "0 以上の値にしてください"
  responses:
    '400':
      description: 入力チェックエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseEntity'
    '500':
      description: サーバーエラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponseEntity'
