########################################
##    アプリケーション共通プロパティ     ##
########################################
# アプリケーション名
spring.application.name=/safetyManagement
# コンテキストルート
server.servlet.context-path=/safetyManagement
# エラー時のレスポンスを設定
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
# ログ設定
logging.config=classpath:logback.xml
# システム設定
spring.config.import=optional:classpath:system.properties,optional:file:/config/system.properties
# 読み込みプロパティファイルの名前
application.name=application
system.name=system

## エラーメッセージ
## メッセージに日本語を用いる場合、Unicodeエスケープシーケンスした値を記載すること
# 404 指定されたページは存在しません
404.error.message=\u6307\u5b9a\u3055\u308c\u305f\u30da\u30fc\u30b8\u306f\u5b58\u5728\u3057\u307e\u305b\u3093
# 400 入力チェックエラー
400.error.message=\u5165\u529b\u30c1\u30a7\u30c3\u30af\u30a8\u30e9\u30fc
# 500 サーバーエラー
500.error.message=\u30b5\u30fc\u30d0\u30fc\u30a8\u30e9\u30fc

## WebClient 設定
# プロキシ
web.client.proxy.url=
web.client.proxy.port=
# タイムアウト
web.client.connect.timeout=5000
web.client.response.timeout=5000

## 非同期処理設定
# プールサイズ
async.core.pool.size=20
async.max.pool.size=20
# キュー
async.Queue.capacity=500

# 風速条件範囲内判定の設定
####
# MVP3までのダミー値(本来は航路情報のDBから取得する)
dummy.wind.speed.range=10
####
#気象要素
weather.wind.elements=ugrd,vgrd
#気象予測対象時間リスト取得のエラーメッセージ
## メッセージに日本語を用いる場合、Unicodeエスケープシーケンスした値を記載すること
# 気象予測対象時間が取得できませんでした。
error.WeatherForecastTime=\u6c17\u8c61\u4e88\u6e2c\u5bfe\u8c61\u6642\u9593\u304c\u53d6\u5f97\u3067\u304d\u307e\u305b\u3093\u3067\u3057\u305f\u3002
# 天候・風速情報の取得のエラーメッセージ
# 天候・風速情報が取得できませんでした。
error.WeatherWindSpeed=\u5929\u5019\u30fb\u98a8\u901f\u60c5\u5831\u304c\u53d6\u5f97\u3067\u304d\u307e\u305b\u3093\u3067\u3057\u305f\u3002

# 鉄道運行予測時刻のバッファ時間
railway.operation.buffer.time=15
# 鉄道運航情報変更通知
railway.service.topic=railwayService/notify/notify

# タスクを実行するレートの設定
operation.task.schedule.rate=600000

# 予約タスクを実行するレートの設定
resevasion.task.schedule.cron.nextday=0 0 8,12,16 * * ?
resevasion.task.schedule.fixedRateString.nowday=600000
# 航路逸脱情報登録を実行する設定
deviation.task.cron.selectRouteDeviationInfo=0 0 0 * * ?
# 機体種別毎の逸脱量・逸脱割合の集計情報実行する設定
deviation.task.cron.aircraftTypeDeviation=0 0 0 1 * ?
# ヒヤリハット情報更新確認処理の実施スケジュール（毎月1日 00:00:00）
# ※指定値補足→左から順に 0秒 0分 0時 1日 毎月 曜日指定なし
task.schedule.cron.checkUpdatesNearMissInfo=0 0 0 1 * ?
# 予約タスク実行の航路状況変化通知でUTM有りに設定
utm.enabled=true

# 適合性評価結果メッセージ
# メッセージに日本語を用いる場合、Unicodeエスケープシーケンスした値を記載すること
# 適合性評価を正常に実行できませんでした。
error.conformity.assessment.message=\u9069\u5408\u6027\u8a55\u4fa1\u3092\u6b63\u5e38\u306b\u5b9f\u884c\u3067\u304d\u307e\u305b\u3093\u3067\u3057\u305f\u3002
# 風速条件範囲内判定エラー
WeatherWindSpeedLogic.conformity.assessment.message=\u98a8\u901f\u6761\u4ef6\u7bc4\u56f2\u5185\u5224\u5b9a\u30a8\u30e9\u30fc
WeatherWindSpeedLogic.conformity.assessment.type=weather
# 第三者立入監視情報判定エラー
ThirdPartyMonitoringInformationEvaluationLogic.conformity.assessment.message=\u7b2c\u4e09\u8005\u7acb\u5165\u76e3\u8996\u60c5\u5831\u5224\u5b9a\u30a8\u30e9\u30fc
ThirdPartyMonitoringInformationEvaluationLogic.conformity.assessment.type=intrusion
# 規制/イベント情報判定エラー
RestrictedAirSpaceEvaluationLogic.conformity.assessment.message=\u898f\u5236/\u30a4\u30d9\u30f3\u30c8\u60c5\u5831\u5224\u5b9a\u30a8\u30e9\u30fc
RestrictedAirSpaceEvaluationLogic.conformity.assessment.type=event
# 鉄道運行情報判定エラー
RailwayOperationInformationEvaluationLogic.conformity.assessment.message=\u9244\u9053\u904b\u884c\u60c5\u5831\u5224\u5b9a\u30a8\u30e9\u30fc
RailwayOperationInformationEvaluationLogic.conformity.assessment.type=railway

# Getting Current Location
error.get.current.location.message=DataNotFoundException
error.get.current.location.description=The uasl reservation ID does not exist in the database, or data within the last 5 seconds does not exist.

# Planned Deviation
error.planned.deviation.message=DataNotFoundException
error.planned.deviation.description=The uasl reservation ID does not exist in the database.

# Register area info of Subscrpition
unlimited.subscription.enabled=false

### MQTT通信設定
# 【機能間IF No.16】予約された航路の適合性評価結果変更通知 【機能間IF No.24】運航中航路状況変更通知 {0}：運航者ID
notify.uaslEvaluation.topic=uasl/operator/{0}/uaslEvaluationNotify
# 【機能間IF No.17】ヒヤリハット情報更新通知 {0}：航路運営者ID
notify.updatesNearMissInfo.topic=uasl/administrator/{0}/nearMiss
# 運行中ドローンの位置情報から逸脱検知
drone.location.topic=uasl/operator/{0}/uaslDeviationNotification
# 安全管理支援(SafetyManagement) 航路予約情報通知
uasl.reservation.topic=uasl/operator/+/uaslReservation/+
#  安全管理支援(SafetyManagement) 規制イベント情報通知
uasl.event.topic=event/updated

## Quality of Service(メッセージ配信の信頼性設定値)
# 最大1回の到達を保証する（=到達を保証できない）
mqtt.qos.atMostOnce=0
# 最低1回の到達を保証する(重複送信する可能性あり)
mqtt.qos.atLeastOnce=1
# 確実に1回の到達を保証する
mqtt.qos.exactryOnce=2

## MQTT クライアントオプション設定
mqtt.connection.timeout=60
mqtt.keep.alive.interval=120
mqtt.fixed.thread.pool=20
mqtt.connect.max.retries=5
mqtt.connect.retry.interval=5000

# MQTT クライアントID設定
mqtt.clientID=mqttSafetyManagementClient
mqtt.subscribe.clientID=mqttSafetyManagementSubscribe

# Management - Health chack
management.endpoints.web.base-path=/admin
management.server.port=48080
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

