########################################
##      環境依存のシステムプロパティ     ##
########################################
########
# airway-reservation-openAPI
########
# 航路予約情報取得
get.airway.reservation.url=http://localhost:7001/airwayReservations/{0}
# 適合性評価結果変化通知
put.notifyConformit.yAssessmentResult.url=http://localhost:7001/safetyManagement/notifyConformity-AssessmentResult
# APIToken
route_reservation.token=0123456789abcdef
########
# sdsp-thirdpartyMonitoring-weather-openAPI
########
# 認証用トークン
token="123456"
# 気象予測対象時間リストの取得 
get.weather.forecast.time.url=http://localhost:7000/safetyManagement/weather-forecast-time
# 天候・風速情報の取得
get.weather.wind.speeds.url=http://localhost:7000/safetyManagement/obtaining-weather-wind-speeds
# 第三者立入監視情報の通知の登録
post.monitoring.notification.destination.registration.url=http://localhost:7000/third-party-entry-notification-registration
# 第三者立入監視情報の通知の変更
put.monitoring.notification.destination.change.url=http://localhost:7000/third-party-entry-notification-change
# 第三者立入監視情報の通知の削除
delete.monitoring.notification.destination.deletion.url=http://localhost:7000/third-party-entry-notification-deletion
# 認証用APIキー
apiKey=0123456789abcdef
# 第三者立入監視情報の取得
get.third.party.monitoring.information.url=http://localhost:7000/api/StorageSystem/intrusions

########
# sdsp-railway-event-openAPI
########
# 規制/イベント情報の取得
post.restricted.air.space.url=http://localhost:7004/event/restrictedAirSpace
# 鉄道運行情報の取得
get.railway.operation.information.url=http://localhost:7004/railwayService/regularDiagram

########
# UTM
########
# endpoint of subscription registration and deletion for telemetry information notifications
subscription.registration.and.deletion.url=http://localhost:7003/api/v1/dronehighway/subscription

##############
# DRONE HIGHWAY
##############
# Drone Highway host
drone.highway.host=http://localhost:8082
##############
# MQTT通信用
##############
# use mqtt.host in system
mqtt.host=localhost
# use mqtt.port in system
mqtt.port=1883
