########################################
##      環境依存のシステムプロパティ     ##
########################################
########
# 航路予約
########
# 航路予約情報取得
get.uasl.reservation.url=http://prism-rev:7004/uaslReservations/{0}
# 適合性評価結果変化通知
put.notify.conformity.assessment.result.url=http://prism-rev:7004/safetyManagement/notifyConformity-AssessmentResult
# APIToken
route_reservation.token=dummy_token_1234567890abcdefghijklmnopqrstuvwxyz
########
# SDSP
########
# 認証用トークン
token="123456"
# 気象予測対象時間リストの取得
get.weather.forecast.time.url=http://prism-third:7004/safetyManagement/weather-forecast-time
# 天候・風速情報の取得
get.weather.wind.speeds.url=http://prism-third:7004/safetyManagement/obtaining-weather-wind-speeds
# 第三者立入監視情報の通知の登録(Optional)
post.monitoring.notification.destination.registration.url=http://prism-third:7004/third-party-entry-notification-registration
# 第三者立入監視情報の通知の変更(Optional)
put.monitoring.notification.destination.change.url=http://prism-third:7004/third-party-entry-notification-change
# 第三者立入監視情報の通知の削除(Optional)
delete.monitoring.notification.destination.deletion.url=http://prism-third:7004/third-party-entry-notification-deletion
# 認証用APIキー
apiKey="dummy_key_abcdefghijklmnopqrstuvwxyz1234567890"
# 第三者立入監視情報の取得
get.third.party.monitoring.information.url=http://prism-third:7004/api/StorageSystem/intrusions

########
# SDSP RestrictedAirSpace,Railway
########
# 規制/イベント情報の取得
post.restricted.air.space.url=http://prism-rail:7004/event/restrictedAirSpace
# 鉄道運行情報の取得
get.railway.operation.information.url=http://prism-rail:7004/railwayService/regularDiagram

########
# UTM
########
# endpoint of subscription registration and deletion for telemetry information notifications
subscription.registration.and.deletion.url=http://prism-utm:7004/api/v1/uasl/subscription

##############
# Uasl
##############
# Uasl host
drone.uasl.host=http://prism-utm:8080
##############
# MQTT通信用
##############
# use mqtt.host in system
mqtt.host=activemq2
# use mqtt.port in system
mqtt.port=1883
