/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.drone_highway.dao;

import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import com.intent_exchange.drone_highway.model.AirwayDeviation;
import com.intent_exchange.drone_highway.model.AirwayDeviationSelect;
@Mapper
@Repository
public interface AirwayDeviationMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_airway_deviation
   *
   * @mbg.generated
   */
  int insertBatchSelective(@Param("rows") List<AirwayDeviation> rows);
  
  List<AirwayDeviation> nermissSelect(AirwayDeviationSelect airwayDeviation);

  /**
   * 指定の期間内に運航が完了した（※）予約のヒヤリハット（航路逸脱）情報を抽出する<br>
   * ※航路予約情報の予約終了日時が指定の期間内である
   *
   * @param startAt 開始日時（抽出対象の予約終了日時に対する条件指定のため注意）
   * @param endAt 終了日時
   */
  List<AirwayDeviation> selectByReservationEndAt(LocalDateTime startAt, LocalDateTime endAt);
}
