/*
 * Copyright 2026 Intent Exchange, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.uasl.model;

import java.io.Serializable;
import java.time.OffsetDateTime;
import lombok.Data;

@Data
public class AircraftTypeDeviation implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aircraft_type_deviation_id
     * @mbg.generated
     */
    private Integer aircraftTypeDeviationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aircraft_info_id
     * @mbg.generated
     */
    private Integer aircraftInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column serial_number
     * @mbg.generated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registration_id
     * @mbg.generated
     */
    private String registrationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column utm_id
     * @mbg.generated
     */
    private String utmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column specific_session_id
     * @mbg.generated
     */
    private String specificSessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_deviation_rate
     * @mbg.generated
     */
    private Double routeDeviationRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_deviation_amount
     * @mbg.generated
     */
    private String routeDeviationAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_deviation_start_time
     * @mbg.generated
     */
    private OffsetDateTime routeDeviationStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route_deviation_end_time
     * @mbg.generated
     */
    private OffsetDateTime routeDeviationEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight_count
     * @mbg.generated
     */
    private Integer flightCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_aircraft_type_deviation
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}