/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.uasl.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class CurrentLocation implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * reservation_id
   * 
   * @mbg.generated
   */
  private String reservationId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * get_location_timestamp
   * 
   * @mbg.generated
   */
  private LocalDateTime timestamp;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * latitude
   * 
   * @mbg.generated
   */
  private Double latitude;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * longitude
   * 
   * @mbg.generated
   */
  private Double longitude;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * altitude
   * 
   * @mbg.generated
   */
  private Integer altitude;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_id
   * 
   * @mbg.generated
   */
  private String uaslId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_section_id
   * 
   * @mbg.generated
   */
  private String uaslSectionId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * operational_status
   * 
   * @mbg.generated
   */
  private String operationalStatus;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * operator_id
   * 
   * @mbg.generated
   */
  private String operatorId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uas_id
   * 
   * @mbg.generated
   */
  private String uasId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * ua_type
   * 
   * @mbg.generated
   */
  private String uaType;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * track_direction
   * 
   * @mbg.generated
   */
  private Integer trackDirection;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * speed
   * 
   * @mbg.generated
   */
  private Double speed;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vertical_speed
   * 
   * @mbg.generated
   */
  private Double verticalSpeed;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * t_drone_location
   * 
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;
}

