/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.uasl.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class MonitoringInformation implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_reservation_id
   * 
   * @mbg.generated
   */
  private String uaslReservationId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * monitoring_information
   * 
   * @mbg.generated
   */
  private String monitoringInformation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_administrator_id
   * 
   * @mbg.generated
   */
  private String uaslAdministratorId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * operator_id
   * 
   * @mbg.generated
   */
  private String operatorId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_id
   * 
   * @mbg.generated
   */
  private String uaslId;
  /***
   * 開始時間
   */
  private LocalDateTime startAt;
  /***
   * 終了時間
   */
  private LocalDateTime endAt;
  /**
   * 座標
   */
  private String coordinates;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * t_monitoring_information
   *
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;
}

