/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.uasl.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Data;

@Data
public class UaslDesignAreaInfoOperation implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_id
   * 
   * @mbg.generated
   */
  private String uaslId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_administrator_id
   * 
   * @mbg.generated
   */
  private String uaslAdministratorId;
  
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * uasl_reservation_id
   * 
   * @mbg.generated
   */
  private String uaslReservationId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * start_at
   * 
   * @mbg.generated
   */
  private LocalDateTime startAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * end_at
   * 
   * @mbg.generated
   */
  private LocalDateTime endAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * operator_id
   * 
   * @mbg.generated
   */
  private String operatorId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * evaluation_results
   * 
   * @mbg.generated
   */
  private Boolean evaluationResults;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * third_party_evaluation_results
   * 
   * @mbg.generated
   */
  private Boolean thirdPartyEvaluationResults;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * railway_operation_evaluation_results
   * 
   * @mbg.generated
   */
  private Boolean railwayOperationEvaluationResults;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * altitude
   * 
   * @mbg.generated
   */
  private String altitude;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * lat_start
   * 
   * @mbg.generated
   */
  private String latStart;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * lon_start
   * 
   * @mbg.generated
   */
  private String lonStart;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * lat_end
   * 
   * @mbg.generated
   */
  private String latEnd;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * lon_end
   * 
   * @mbg.generated
   */
  private String lonEnd;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * geometry
   * 
   * @mbg.generated
   */
  private Object geometry;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * area_info
   * 
   * @mbg.generated
   */
  private String areaInfo;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * railway_crossing_info
   * 
   * @mbg.generated
   */
  private String railwayCrossingInfo;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * v_uasl_design_area_info_operation
   *
   * @mbg.generated
   */
  private static final long serialVersionUID = 1L;

  /** 第三者立入判定 */
  private Boolean restricted = false;
}

