/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.intent_exchange.uasl.api;

import com.intent_exchange.uasl.entity.ActiveReservationResponse;
import com.intent_exchange.uasl.entity.ErrorResponseEntity;
import com.intent_exchange.uasl.entity.SearchActiveUaslReservationsRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-09T14:24:35.115008009+09:00[Asia/Tokyo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "active-uasl-reservations", description = "有効な予約情報の照会")
public interface ActiveUaslReservationsApi {

    /**
     * POST /active-uasl-reservations : 有効な航路予約の照会
     * 入力された航路区画IDリストをもとに、サーバ側で判定に使用した現在時刻と予約終了日時を比較し、 予約終了日時を迎えていない有効な航路予約情報を返却する。   入力された航路区画IDに存在しないものが含まれていてもエラーとしない。   入力された航路区画IDが存在しない航路区画IDのみであった場合は、 有効な予約情報がない場合と同様に空配列を返却する。   入力された航路区画IDに存在するものとしないものが混在している場合は、 存在する航路区画IDの照会結果を返却する。 
     *
     * @param searchActiveUaslReservationsRequest  (required)
     * @return 正常終了 (status code 200)
     *         or リクエスト不正。 リクエストボディの&#x60;uaslSectionIds&#x60; が未指定、または型不正。  (status code 400)
     *         or サーバ内部エラー (status code 500)
     */
    @Operation(
        operationId = "searchActiveUaslReservations",
        summary = "有効な航路予約の照会",
        description = "入力された航路区画IDリストをもとに、サーバ側で判定に使用した現在時刻と予約終了日時を比較し、 予約終了日時を迎えていない有効な航路予約情報を返却する。   入力された航路区画IDに存在しないものが含まれていてもエラーとしない。   入力された航路区画IDが存在しない航路区画IDのみであった場合は、 有効な予約情報がない場合と同様に空配列を返却する。   入力された航路区画IDに存在するものとしないものが混在している場合は、 存在する航路区画IDの照会結果を返却する。 ",
        tags = { "active-uasl-reservations" },
        responses = {
            @ApiResponse(responseCode = "200", description = "正常終了", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ActiveReservationResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエスト不正。 リクエストボディの`uaslSectionIds` が未指定、または型不正。 ", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバ内部エラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/active-uasl-reservations",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ActiveReservationResponse> searchActiveUaslReservations(
        @Parameter(name = "SearchActiveUaslReservationsRequest", description = "", required = true) @Valid @RequestBody SearchActiveUaslReservationsRequest searchActiveUaslReservationsRequest
    );

}
