/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.intent_exchange.uasl.api;

import com.intent_exchange.uasl.entity.ConformityAssessmentExecutionEntity;
import com.intent_exchange.uasl.entity.ConformityAssessmentResponseEntity;
import com.intent_exchange.uasl.entity.ErrorResponseEntity;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-02-05T16:53:06.485800400+09:00[Asia/Tokyo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "ConformityAssessment", description = "安全管理支援(SafetyManagement)のコントローラクラス。")
public interface ConformityAssessmentApi {

    /**
     * POST /conformity-assessment : 航路の適合性評価実行
     * 適合性評価に必要な情報を受信し、航路予約へ航路の適合性評価の結果を送信します。
     *
     * @param conformityAssessmentExecutionEntity  (required)
     * @return 適合性評価結果OK (status code 200)
     *         or 適合性評価結果NG (status code 400)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "executionConformityAssessment",
        summary = "航路の適合性評価実行",
        description = "適合性評価に必要な情報を受信し、航路予約へ航路の適合性評価の結果を送信します。",
        tags = { "ConformityAssessment" },
        responses = {
            @ApiResponse(responseCode = "200", description = "適合性評価結果OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ConformityAssessmentResponseEntity.class))
            }),
            @ApiResponse(responseCode = "400", description = "適合性評価結果NG", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/conformity-assessment",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ConformityAssessmentResponseEntity> executionConformityAssessment(
        @Parameter(name = "ConformityAssessmentExecutionEntity", description = "", required = true) @Valid @RequestBody ConformityAssessmentExecutionEntity conformityAssessmentExecutionEntity
    );

}

