/*
 * Copyright 2026 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.intent_exchange.uasl.api;

import java.util.Date;
import org.springframework.format.annotation.DateTimeFormat;
import com.intent_exchange.uasl.entity.ErrorResponse;
import com.intent_exchange.uasl.entity.FlightLogListResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-28T13:43:13.092416900+09:00[Asia/Tokyo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "flight-logs", description = "フライトログ")
public interface FlightLogsApi {

    /**
     * GET /flight-logs : フライトログ取得API
     * 安全管理の運行情報蓄積テーブルから、指定された条件に基づいて運航履歴データを検索します。 時刻はUTCです。  **必須パラメータ:** - startTime: 検索開始時刻（ISO 8601形式） - endTime: 検索終了時刻（ISO 8601形式）  **オプションパラメータ:** - reservationId: 特定の航路予約IDで絞り込み - uaslId: 特定の航路IDで絞り込み - operatorId: 特定の運航者IDで絞り込み - aircraftInfoId: 特定の機体情報IDで絞り込み - uaType: 機体種別で絞り込み  **注意事項:** - 検索期間は最大31日間まで指定可能です - データは取得日時の降順（最新から古い順）で返却されます 
     *
     * @param startTime 検索開始時刻（ISO 8601形式: YYYY-MM-DDTHH:mm:ss.SSSZ） 指定された時刻以降のデータを取得します。  (required)
     * @param endTime 検索終了時刻（ISO 8601形式: YYYY-MM-DDTHH:mm:ss.SSSZ） 指定された時刻以前のデータを取得します。  (required)
     * @param reservationId 航路予約ID（完全一致検索） (optional)
     * @param uaslId 航路ID（完全一致検索） (optional)
     * @param operatorId 運航者ID（完全一致検索） (optional)
     * @param aircraftInfoId 機体情報ID（完全一致検索） (optional)
     * @param uaType 機体種別（完全一致検索） (optional)
     * @return 検索成功 (status code 200)
     *         or リクエストが不正 (status code 400)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "getFlightLogs",
        summary = "フライトログ取得API",
        description = "安全管理の運行情報蓄積テーブルから、指定された条件に基づいて運航履歴データを検索します。 時刻はUTCです。  **必須パラメータ:** - startTime: 検索開始時刻（ISO 8601形式） - endTime: 検索終了時刻（ISO 8601形式）  **オプションパラメータ:** - reservationId: 特定の航路予約IDで絞り込み - uaslId: 特定の航路IDで絞り込み - operatorId: 特定の運航者IDで絞り込み - aircraftInfoId: 特定の機体情報IDで絞り込み - uaType: 機体種別で絞り込み  **注意事項:** - 検索期間は最大31日間まで指定可能です - データは取得日時の降順（最新から古い順）で返却されます ",
        tags = { "flight-logs" },
        responses = {
            @ApiResponse(responseCode = "200", description = "検索成功", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FlightLogListResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "リクエストが不正", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/flight-logs",
        produces = { "application/json" }
    )
    
    ResponseEntity<FlightLogListResponse> getFlightLogs(
        @NotNull @Parameter(name = "startTime", description = "検索開始時刻（ISO 8601形式: YYYY-MM-DDTHH:mm:ss.SSSZ） 指定された時刻以降のデータを取得します。 ", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "startTime", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) String startTime,
        @NotNull @Parameter(name = "endTime", description = "検索終了時刻（ISO 8601形式: YYYY-MM-DDTHH:mm:ss.SSSZ） 指定された時刻以前のデータを取得します。 ", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "endTime", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) String endTime,
        @Size(max = 255) @Parameter(name = "reservationId", description = "航路予約ID（完全一致検索）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "reservationId", required = false) String reservationId,
        @Size(max = 255) @Parameter(name = "uaslId", description = "航路ID（完全一致検索）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "uaslId", required = false) String uaslId,
        @Size(max = 255) @Parameter(name = "operatorId", description = "運航者ID（完全一致検索）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "operatorId", required = false) String operatorId,
        @Min(0) @Max(9999) @Parameter(name = "aircraftInfoId", description = "機体情報ID（完全一致検索）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "aircraftInfoId", required = false) Integer aircraftInfoId,
        @Size(max = 255) @Parameter(name = "uaType", description = "機体種別（完全一致検索）", in = ParameterIn.QUERY) @Valid @RequestParam(value = "uaType", required = false) String uaType
    );

}
