/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.intent_exchange.uasl.api;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import com.intent_exchange.uasl.entity.ErrorResponseEntity;
import com.intent_exchange.uasl.entity.PlannedDeviationEntity;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-12-02T15:00:01.104906100+09:00[Asia/Tokyo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "PlannedDeviation", description = "計画的な航路逸脱の設定")
public interface PlannedDeviationApi {

    /**
     * GET /planned-deviation/{reservationId} : 計画的な航路逸脱の設定状態取得
     * 計画的な航路逸脱の設定状態を取得する。
     *
     * @param reservationId 航路予約毎の識別ID (required)
     * @return 正常終了 (status code 200)
     *         or 航路予約IDがDBに存在しなかった場合 (status code 404)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "getPlannedDeviation",
        summary = "計画的な航路逸脱の設定状態取得",
        description = "計画的な航路逸脱の設定状態を取得する。",
        tags = { "PlannedDeviation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "正常終了", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = PlannedDeviationEntity.class))
            }),
            @ApiResponse(responseCode = "404", description = "航路予約IDがDBに存在しなかった場合", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/planned-deviation/{reservationId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<PlannedDeviationEntity> getPlannedDeviation(
        @Parameter(name = "reservationId", description = "航路予約毎の識別ID", required = true, in = ParameterIn.PATH) @PathVariable("reservationId") String reservationId
    );


    /**
     * PUT /planned-deviation/{reservationId} : 計画的な航路逸脱の設定
     * 指定した航路予約毎の識別IDに対応する予約情報の「計画した航路逸脱」を変更する。
     *
     * @param reservationId 航路予約毎の識別ID (required)
     * @param enabled 計画的な航路逸脱の指示。 - true: 計画的な逸脱として扱う - false: 通常の逸脱として扱う  (required)
     * @return 正常終了 (status code 204)
     *         or 入力チェックエラー (status code 400)
     *         or 航路予約IDがDBに存在しなかった場合 (status code 404)
     *         or サーバーエラー (status code 500)
     */
    @Operation(
        operationId = "setPlannedDeviation",
        summary = "計画的な航路逸脱の設定",
        description = "指定した航路予約毎の識別IDに対応する予約情報の「計画した航路逸脱」を変更する。",
        tags = { "PlannedDeviation" },
        responses = {
            @ApiResponse(responseCode = "204", description = "正常終了"),
            @ApiResponse(responseCode = "400", description = "入力チェックエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "404", description = "航路予約IDがDBに存在しなかった場合", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            }),
            @ApiResponse(responseCode = "500", description = "サーバーエラー", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponseEntity.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/planned-deviation/{reservationId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> setPlannedDeviation(
        @Parameter(name = "reservationId", description = "航路予約毎の識別ID", required = true, in = ParameterIn.PATH) @PathVariable("reservationId") String reservationId,
        @NotNull @Parameter(name = "enabled", description = "計画的な航路逸脱の指示。 - true: 計画的な逸脱として扱う - false: 通常の逸脱として扱う ", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "enabled", required = true) Boolean enabled
    );

}
