/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package com.intent_exchange.uasl.api;

import javax.annotation.Generated;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.intent_exchange.uasl.entity.ErrorResponseEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2024-11-28T09:42:11.724536400+09:00[Asia/Tokyo]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "UaslReservation", description = "安全管理支援(SafetyManagement)のコントローラクラス。")
public interface UaslReservationApi {

  /**
   * DELETE /uasl-reservation-deletion/{uaslReservationId} : 航路予約情報の削除
   * 航路の安全管理支援(SafetyManagement)へ通知した航路予約情報を削除する。
   *
   * @param uaslReservationId 航路予約毎の識別ID (required)
   * @return 削除成功 (status code 204) or 入力チェックエラー (status code 400) or サーバーエラー (status code 500)
   */
  @Operation(operationId = "deleteUaslReservation", summary = "航路予約情報の削除",
      description = "航路の安全管理支援(SafetyManagement)へ通知した航路予約情報を削除する。", tags = {"UaslReservation"},
      responses = {@ApiResponse(responseCode = "204", description = "削除成功"),
          @ApiResponse(responseCode = "400", description = "入力チェックエラー",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponseEntity.class))}),
          @ApiResponse(responseCode = "500", description = "サーバーエラー",
              content = {@Content(mediaType = "application/json",
                  schema = @Schema(implementation = ErrorResponseEntity.class))})})
  @RequestMapping(method = RequestMethod.DELETE,
      value = "/uasl-reservation-deletion/{uaslReservationId}", produces = {"application/json"})

  ResponseEntity<Void> deleteUaslReservation(
      @Parameter(name = "uaslReservationId", description = "航路予約毎の識別ID", required = true,
          in = ParameterIn.PATH) @PathVariable("uaslReservationId") String uaslReservationId);

}

