/*
 * Copyright 2026 Intent Exchange, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.uasl.dao;

import com.intent_exchange.uasl.model.AircraftTypeDeviation;
import com.intent_exchange.uasl.model.AircraftTypeDeviationInfo;
import java.sql.Timestamp;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface AircraftTypeDeviationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aircraft_type_deviation
     *
     * @mbg.generated
     */
    int insert(AircraftTypeDeviation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aircraft_type_deviation
     *
     * @mbg.generated
     */
    int insertSelective(AircraftTypeDeviation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aircraft_type_deviation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AircraftTypeDeviation row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_aircraft_type_deviation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AircraftTypeDeviation row);

    /**
     * メタデータ付きで、左閉右開区間 [periodStart, periodEnd) の逸脱情報をページング取得します。
     * 大量データを一度に読み込まないように、メモリ負荷を抑えるためのページングです。
     *
     * @param periodStart 期間開始（含む）
     * @param periodEnd 期間終了（排除）
     * @param limit 取得件数
     * @param offset 取得開始位置
     */
    List<AircraftTypeDeviationInfo> selectRouteDeviationInfoForPeriodPaged(
        @Param("periodStart") Timestamp periodStart,
        @Param("periodEnd") Timestamp periodEnd,
        @Param("limit") int limit,
        @Param("offset") int offset);
}