/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.uasl.dao;

import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.intent_exchange.uasl.model.UaslReservation;

@Mapper
@Repository
public interface UaslReservationMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_uasl_reservation
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(@Param("uaslReservationId") String uaslReservationId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_uasl_reservation
   *
   * @mbg.generated
   */
  int upsertSelective(UaslReservation row);
  
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table 
   * t_uasl_reservation
   * 
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(UaslReservation row);

  /**
   * 航路予約毎の識別IDに該当する計画的な航路逸脱フラグを取得する。
   *
   * @param uaslReservationId 航路予約毎の識別ID
   * @return 計画的な航路逸脱フラグ（予約が存在しない場合はnull）
   */
  Boolean getPlannedDeviation(String uaslReservationId);

  /**
   * 指定された航路区画IDと重複する有効な予約情報を取得する。
   *
   * @param uaslSectionIds 航路区画IDリスト
   * @param now 取得基準時刻（end_at がこの時刻より後）
   * @return 条件に合致する予約情報リスト
   */
  List<UaslReservation> selectActiveBySectionIds(
      @Param("uaslSectionIds") List<String> uaslSectionIds, @Param("now") LocalDateTime now);

  /**
   * 航路予約毎の識別ID、またはメーカー名・型番に紐づく機体の最大風速を取得する。
   *
   * @param uaslReservationId 航路予約毎の識別ID (指定がある場合優先)
   * @param maker メーカー名 (uaslReservationId指定なしの場合に使用)
   * @param modelNumber 型番 (uaslReservationId指定なしの場合に使用)
   * @return 最大風速 (m/s)
   */
  Double selectMaxWindSpeed(@Param("uaslReservationId") String uaslReservationId,
      @Param("maker") String maker, @Param("modelNumber") String modelNumber);
}
