/*
 * Copyright 2025 Intent Exchange, Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package com.intent_exchange.drone_highway.model;

import java.io.Serializable;
import java.sql.Timestamp;
import lombok.Data;

@Data
public class AirwayDesignAreaInfoDeviation implements Serializable {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * reservation_id
   * 
   * @mbg.generated
   */
  private String reservationId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * get_location_timestamp
   * 
   * @mbg.generated
   */
  private Timestamp getLocationTimestamp;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * latitude
   * 
   * @mbg.generated
   */
  private Double latitude;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * longitude
   * 
   * @mbg.generated
   */
  private Double longitude;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * above_ground_level
   * 
   * @mbg.generated
   */
  private Integer aboveGroundLevel;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * route_deviation_rate
   * 
   * @mbg.generated
   */
  private Double routeDeviationRate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * horizontal_deviation
   * 
   * @mbg.generated
   */
  private Double horizontalDeviation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * vertical_deviation
   * 
   * @mbg.generated
   */
  private Double verticalDeviation;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * airway_id
   * 
   * @mbg.generated
   */
  private String airwayId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * airway_section_id
   * 
   * @mbg.generated
   */
  private String airwaySectionId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * operator_id
   * 
   * @mbg.generated
   */
  private String operatorId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * aircraftInfoId
   * 
   * @mbg.generated
   */
  private Integer aircraftInfoId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * airway_operator_id
   * 
   * @mbg.generated
   */
  private String airwayAdministratorId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * end_at
   * 
   * @mbg.generated
   */
  private Timestamp endAt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * operational_status
   * 
   * @mbg.generated
   */
  private String operationalStatus;

  private static final long serialVersionUID = 1L;
}

